// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.talking.grpc.users;

public interface GetUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUsersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 limit = 1;</code>
   */
  int getLimit();

  /**
   * <code>.google.protobuf.Timestamp maxOnlineDatetime = 2;</code>
   */
  boolean hasMaxOnlineDatetime();
  /**
   * <code>.google.protobuf.Timestamp maxOnlineDatetime = 2;</code>
   */
  com.google.protobuf.Timestamp getMaxOnlineDatetime();
  /**
   * <code>.google.protobuf.Timestamp maxOnlineDatetime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getMaxOnlineDatetimeOrBuilder();
}
