// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.talking.grpc.users;

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();
}
