// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.talking.grpc.users;

public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.common.User user = 1;</code>
   */
  com.talking.grpc.common.User getUser();
  /**
   * <code>.common.User user = 1;</code>
   */
  com.talking.grpc.common.UserOrBuilder getUserOrBuilder();
}
