// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.talking.grpc.users;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\032\037google/protobuf/time" +
      "stamp.proto\032\036google/protobuf/wrappers.pr" +
      "oto\032\rcommons.proto\"W\n\017GetUsersRequest\022\r\n" +
      "\005limit\030\001 \001(\005\0225\n\021maxOnlineDatetime\030\002 \001(\0132" +
      "\032.google.protobuf.Timestamp\"/\n\020GetUsersR" +
      "esponse\022\033\n\005users\030\001 \003(\0132\014.common.User\" \n\016" +
      "GetUserRequest\022\016\n\006userId\030\001 \001(\005\"-\n\017GetUse" +
      "rResponse\022\032\n\004user\030\001 \001(\0132\014.common.User2\204\001" +
      "\n\013UserService\0229\n\010GetUsers\022\025.user.GetUser" +
      "sRequest\032\026.user.GetUsersResponse\022:\n\013GetU" +
      "serById\022\024.user.GetUserRequest\032\025.user.Get" +
      "UserResponseB\032\n\026com.talking.grpc.usersP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.talking.grpc.common.Commons.getDescriptor(),
        }, assigner);
    internal_static_user_GetUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_GetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUsersRequest_descriptor,
        new java.lang.String[] { "Limit", "MaxOnlineDatetime", });
    internal_static_user_GetUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_GetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_user_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.talking.grpc.common.Commons.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
