// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.talking.grpc.common;

public final class Commons {
  private Commons() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ProfileImage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ProfileImage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommons.proto\022\006common\032\037google/protobuf" +
      "/timestamp.proto\032\036google/protobuf/wrappe" +
      "rs.proto\"\240\002\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 " +
      "\001(\t\022&\n\ngenderType\030\003 \001(\0162\022.common.GenderT" +
      "ype\022\013\n\003age\030\004 \001(\005\022\n\n\002pr\030\005 \001(\t\022*\n\014profileI" +
      "mage\030\006 \001(\0132\024.common.ProfileImage\0226\n\022last" +
      "OnlineDatetime\030\007 \001(\0132\032.google.protobuf.T" +
      "imestamp\022+\n\007created\030\010 \001(\0132\032.google.proto" +
      "buf.Timestamp\022,\n\010modified\030\t \001(\0132\032.google" +
      ".protobuf.Timestamp\"\337\001\n\014ProfileImage\0226\n\020" +
      "imageOriginalUrl\030\001 \001(\0132\034.google.protobuf" +
      ".StringValue\0221\n\013image100Url\030\002 \001(\0132\034.goog" +
      "le.protobuf.StringValue\0221\n\013image300Url\030\003" +
      " \001(\0132\034.google.protobuf.StringValue\0221\n\013im" +
      "age600Url\030\004 \001(\0132\034.google.protobuf.String" +
      "Value*\"\n\nGenderType\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020" +
      "\001B\033\n\027com.talking.grpc.commonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_common_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_User_descriptor,
        new java.lang.String[] { "Id", "Name", "GenderType", "Age", "Pr", "ProfileImage", "LastOnlineDatetime", "Created", "Modified", });
    internal_static_common_ProfileImage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_ProfileImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ProfileImage_descriptor,
        new java.lang.String[] { "ImageOriginalUrl", "Image100Url", "Image300Url", "Image600Url", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
