// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.talking.grpc.common;

/**
 * Protobuf type {@code common.ProfileImage}
 */
public  final class ProfileImage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.ProfileImage)
    ProfileImageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProfileImage.newBuilder() to construct.
  private ProfileImage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProfileImage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProfileImage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (imageOriginalUrl_ != null) {
              subBuilder = imageOriginalUrl_.toBuilder();
            }
            imageOriginalUrl_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imageOriginalUrl_);
              imageOriginalUrl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (image100Url_ != null) {
              subBuilder = image100Url_.toBuilder();
            }
            image100Url_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image100Url_);
              image100Url_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (image300Url_ != null) {
              subBuilder = image300Url_.toBuilder();
            }
            image300Url_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image300Url_);
              image300Url_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (image600Url_ != null) {
              subBuilder = image600Url_.toBuilder();
            }
            image600Url_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image600Url_);
              image600Url_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talking.grpc.common.Commons.internal_static_common_ProfileImage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talking.grpc.common.Commons.internal_static_common_ProfileImage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talking.grpc.common.ProfileImage.class, com.talking.grpc.common.ProfileImage.Builder.class);
  }

  public static final int IMAGEORIGINALURL_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue imageOriginalUrl_;
  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  public boolean hasImageOriginalUrl() {
    return imageOriginalUrl_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  public com.google.protobuf.StringValue getImageOriginalUrl() {
    return imageOriginalUrl_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : imageOriginalUrl_;
  }
  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getImageOriginalUrlOrBuilder() {
    return getImageOriginalUrl();
  }

  public static final int IMAGE100URL_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue image100Url_;
  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  public boolean hasImage100Url() {
    return image100Url_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  public com.google.protobuf.StringValue getImage100Url() {
    return image100Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image100Url_;
  }
  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getImage100UrlOrBuilder() {
    return getImage100Url();
  }

  public static final int IMAGE300URL_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue image300Url_;
  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  public boolean hasImage300Url() {
    return image300Url_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  public com.google.protobuf.StringValue getImage300Url() {
    return image300Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image300Url_;
  }
  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getImage300UrlOrBuilder() {
    return getImage300Url();
  }

  public static final int IMAGE600URL_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue image600Url_;
  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  public boolean hasImage600Url() {
    return image600Url_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  public com.google.protobuf.StringValue getImage600Url() {
    return image600Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image600Url_;
  }
  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getImage600UrlOrBuilder() {
    return getImage600Url();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (imageOriginalUrl_ != null) {
      output.writeMessage(1, getImageOriginalUrl());
    }
    if (image100Url_ != null) {
      output.writeMessage(2, getImage100Url());
    }
    if (image300Url_ != null) {
      output.writeMessage(3, getImage300Url());
    }
    if (image600Url_ != null) {
      output.writeMessage(4, getImage600Url());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (imageOriginalUrl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImageOriginalUrl());
    }
    if (image100Url_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getImage100Url());
    }
    if (image300Url_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getImage300Url());
    }
    if (image600Url_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getImage600Url());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talking.grpc.common.ProfileImage)) {
      return super.equals(obj);
    }
    com.talking.grpc.common.ProfileImage other = (com.talking.grpc.common.ProfileImage) obj;

    boolean result = true;
    result = result && (hasImageOriginalUrl() == other.hasImageOriginalUrl());
    if (hasImageOriginalUrl()) {
      result = result && getImageOriginalUrl()
          .equals(other.getImageOriginalUrl());
    }
    result = result && (hasImage100Url() == other.hasImage100Url());
    if (hasImage100Url()) {
      result = result && getImage100Url()
          .equals(other.getImage100Url());
    }
    result = result && (hasImage300Url() == other.hasImage300Url());
    if (hasImage300Url()) {
      result = result && getImage300Url()
          .equals(other.getImage300Url());
    }
    result = result && (hasImage600Url() == other.hasImage600Url());
    if (hasImage600Url()) {
      result = result && getImage600Url()
          .equals(other.getImage600Url());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImageOriginalUrl()) {
      hash = (37 * hash) + IMAGEORIGINALURL_FIELD_NUMBER;
      hash = (53 * hash) + getImageOriginalUrl().hashCode();
    }
    if (hasImage100Url()) {
      hash = (37 * hash) + IMAGE100URL_FIELD_NUMBER;
      hash = (53 * hash) + getImage100Url().hashCode();
    }
    if (hasImage300Url()) {
      hash = (37 * hash) + IMAGE300URL_FIELD_NUMBER;
      hash = (53 * hash) + getImage300Url().hashCode();
    }
    if (hasImage600Url()) {
      hash = (37 * hash) + IMAGE600URL_FIELD_NUMBER;
      hash = (53 * hash) + getImage600Url().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talking.grpc.common.ProfileImage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.common.ProfileImage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.ProfileImage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.ProfileImage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talking.grpc.common.ProfileImage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.ProfileImage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.ProfileImage)
      com.talking.grpc.common.ProfileImageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talking.grpc.common.Commons.internal_static_common_ProfileImage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talking.grpc.common.Commons.internal_static_common_ProfileImage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talking.grpc.common.ProfileImage.class, com.talking.grpc.common.ProfileImage.Builder.class);
    }

    // Construct using com.talking.grpc.common.ProfileImage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (imageOriginalUrlBuilder_ == null) {
        imageOriginalUrl_ = null;
      } else {
        imageOriginalUrl_ = null;
        imageOriginalUrlBuilder_ = null;
      }
      if (image100UrlBuilder_ == null) {
        image100Url_ = null;
      } else {
        image100Url_ = null;
        image100UrlBuilder_ = null;
      }
      if (image300UrlBuilder_ == null) {
        image300Url_ = null;
      } else {
        image300Url_ = null;
        image300UrlBuilder_ = null;
      }
      if (image600UrlBuilder_ == null) {
        image600Url_ = null;
      } else {
        image600Url_ = null;
        image600UrlBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talking.grpc.common.Commons.internal_static_common_ProfileImage_descriptor;
    }

    public com.talking.grpc.common.ProfileImage getDefaultInstanceForType() {
      return com.talking.grpc.common.ProfileImage.getDefaultInstance();
    }

    public com.talking.grpc.common.ProfileImage build() {
      com.talking.grpc.common.ProfileImage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.talking.grpc.common.ProfileImage buildPartial() {
      com.talking.grpc.common.ProfileImage result = new com.talking.grpc.common.ProfileImage(this);
      if (imageOriginalUrlBuilder_ == null) {
        result.imageOriginalUrl_ = imageOriginalUrl_;
      } else {
        result.imageOriginalUrl_ = imageOriginalUrlBuilder_.build();
      }
      if (image100UrlBuilder_ == null) {
        result.image100Url_ = image100Url_;
      } else {
        result.image100Url_ = image100UrlBuilder_.build();
      }
      if (image300UrlBuilder_ == null) {
        result.image300Url_ = image300Url_;
      } else {
        result.image300Url_ = image300UrlBuilder_.build();
      }
      if (image600UrlBuilder_ == null) {
        result.image600Url_ = image600Url_;
      } else {
        result.image600Url_ = image600UrlBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talking.grpc.common.ProfileImage) {
        return mergeFrom((com.talking.grpc.common.ProfileImage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talking.grpc.common.ProfileImage other) {
      if (other == com.talking.grpc.common.ProfileImage.getDefaultInstance()) return this;
      if (other.hasImageOriginalUrl()) {
        mergeImageOriginalUrl(other.getImageOriginalUrl());
      }
      if (other.hasImage100Url()) {
        mergeImage100Url(other.getImage100Url());
      }
      if (other.hasImage300Url()) {
        mergeImage300Url(other.getImage300Url());
      }
      if (other.hasImage600Url()) {
        mergeImage600Url(other.getImage600Url());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talking.grpc.common.ProfileImage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talking.grpc.common.ProfileImage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue imageOriginalUrl_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> imageOriginalUrlBuilder_;
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public boolean hasImageOriginalUrl() {
      return imageOriginalUrlBuilder_ != null || imageOriginalUrl_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public com.google.protobuf.StringValue getImageOriginalUrl() {
      if (imageOriginalUrlBuilder_ == null) {
        return imageOriginalUrl_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : imageOriginalUrl_;
      } else {
        return imageOriginalUrlBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public Builder setImageOriginalUrl(com.google.protobuf.StringValue value) {
      if (imageOriginalUrlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageOriginalUrl_ = value;
        onChanged();
      } else {
        imageOriginalUrlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public Builder setImageOriginalUrl(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (imageOriginalUrlBuilder_ == null) {
        imageOriginalUrl_ = builderForValue.build();
        onChanged();
      } else {
        imageOriginalUrlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public Builder mergeImageOriginalUrl(com.google.protobuf.StringValue value) {
      if (imageOriginalUrlBuilder_ == null) {
        if (imageOriginalUrl_ != null) {
          imageOriginalUrl_ =
            com.google.protobuf.StringValue.newBuilder(imageOriginalUrl_).mergeFrom(value).buildPartial();
        } else {
          imageOriginalUrl_ = value;
        }
        onChanged();
      } else {
        imageOriginalUrlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public Builder clearImageOriginalUrl() {
      if (imageOriginalUrlBuilder_ == null) {
        imageOriginalUrl_ = null;
        onChanged();
      } else {
        imageOriginalUrl_ = null;
        imageOriginalUrlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getImageOriginalUrlBuilder() {
      
      onChanged();
      return getImageOriginalUrlFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getImageOriginalUrlOrBuilder() {
      if (imageOriginalUrlBuilder_ != null) {
        return imageOriginalUrlBuilder_.getMessageOrBuilder();
      } else {
        return imageOriginalUrl_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : imageOriginalUrl_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getImageOriginalUrlFieldBuilder() {
      if (imageOriginalUrlBuilder_ == null) {
        imageOriginalUrlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getImageOriginalUrl(),
                getParentForChildren(),
                isClean());
        imageOriginalUrl_ = null;
      }
      return imageOriginalUrlBuilder_;
    }

    private com.google.protobuf.StringValue image100Url_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> image100UrlBuilder_;
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public boolean hasImage100Url() {
      return image100UrlBuilder_ != null || image100Url_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public com.google.protobuf.StringValue getImage100Url() {
      if (image100UrlBuilder_ == null) {
        return image100Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image100Url_;
      } else {
        return image100UrlBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public Builder setImage100Url(com.google.protobuf.StringValue value) {
      if (image100UrlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image100Url_ = value;
        onChanged();
      } else {
        image100UrlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public Builder setImage100Url(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (image100UrlBuilder_ == null) {
        image100Url_ = builderForValue.build();
        onChanged();
      } else {
        image100UrlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public Builder mergeImage100Url(com.google.protobuf.StringValue value) {
      if (image100UrlBuilder_ == null) {
        if (image100Url_ != null) {
          image100Url_ =
            com.google.protobuf.StringValue.newBuilder(image100Url_).mergeFrom(value).buildPartial();
        } else {
          image100Url_ = value;
        }
        onChanged();
      } else {
        image100UrlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public Builder clearImage100Url() {
      if (image100UrlBuilder_ == null) {
        image100Url_ = null;
        onChanged();
      } else {
        image100Url_ = null;
        image100UrlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getImage100UrlBuilder() {
      
      onChanged();
      return getImage100UrlFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getImage100UrlOrBuilder() {
      if (image100UrlBuilder_ != null) {
        return image100UrlBuilder_.getMessageOrBuilder();
      } else {
        return image100Url_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : image100Url_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue image100Url = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getImage100UrlFieldBuilder() {
      if (image100UrlBuilder_ == null) {
        image100UrlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getImage100Url(),
                getParentForChildren(),
                isClean());
        image100Url_ = null;
      }
      return image100UrlBuilder_;
    }

    private com.google.protobuf.StringValue image300Url_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> image300UrlBuilder_;
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public boolean hasImage300Url() {
      return image300UrlBuilder_ != null || image300Url_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public com.google.protobuf.StringValue getImage300Url() {
      if (image300UrlBuilder_ == null) {
        return image300Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image300Url_;
      } else {
        return image300UrlBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public Builder setImage300Url(com.google.protobuf.StringValue value) {
      if (image300UrlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image300Url_ = value;
        onChanged();
      } else {
        image300UrlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public Builder setImage300Url(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (image300UrlBuilder_ == null) {
        image300Url_ = builderForValue.build();
        onChanged();
      } else {
        image300UrlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public Builder mergeImage300Url(com.google.protobuf.StringValue value) {
      if (image300UrlBuilder_ == null) {
        if (image300Url_ != null) {
          image300Url_ =
            com.google.protobuf.StringValue.newBuilder(image300Url_).mergeFrom(value).buildPartial();
        } else {
          image300Url_ = value;
        }
        onChanged();
      } else {
        image300UrlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public Builder clearImage300Url() {
      if (image300UrlBuilder_ == null) {
        image300Url_ = null;
        onChanged();
      } else {
        image300Url_ = null;
        image300UrlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getImage300UrlBuilder() {
      
      onChanged();
      return getImage300UrlFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getImage300UrlOrBuilder() {
      if (image300UrlBuilder_ != null) {
        return image300UrlBuilder_.getMessageOrBuilder();
      } else {
        return image300Url_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : image300Url_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue image300Url = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getImage300UrlFieldBuilder() {
      if (image300UrlBuilder_ == null) {
        image300UrlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getImage300Url(),
                getParentForChildren(),
                isClean());
        image300Url_ = null;
      }
      return image300UrlBuilder_;
    }

    private com.google.protobuf.StringValue image600Url_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> image600UrlBuilder_;
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public boolean hasImage600Url() {
      return image600UrlBuilder_ != null || image600Url_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public com.google.protobuf.StringValue getImage600Url() {
      if (image600UrlBuilder_ == null) {
        return image600Url_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : image600Url_;
      } else {
        return image600UrlBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public Builder setImage600Url(com.google.protobuf.StringValue value) {
      if (image600UrlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image600Url_ = value;
        onChanged();
      } else {
        image600UrlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public Builder setImage600Url(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (image600UrlBuilder_ == null) {
        image600Url_ = builderForValue.build();
        onChanged();
      } else {
        image600UrlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public Builder mergeImage600Url(com.google.protobuf.StringValue value) {
      if (image600UrlBuilder_ == null) {
        if (image600Url_ != null) {
          image600Url_ =
            com.google.protobuf.StringValue.newBuilder(image600Url_).mergeFrom(value).buildPartial();
        } else {
          image600Url_ = value;
        }
        onChanged();
      } else {
        image600UrlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public Builder clearImage600Url() {
      if (image600UrlBuilder_ == null) {
        image600Url_ = null;
        onChanged();
      } else {
        image600Url_ = null;
        image600UrlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getImage600UrlBuilder() {
      
      onChanged();
      return getImage600UrlFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getImage600UrlOrBuilder() {
      if (image600UrlBuilder_ != null) {
        return image600UrlBuilder_.getMessageOrBuilder();
      } else {
        return image600Url_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : image600Url_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue image600Url = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getImage600UrlFieldBuilder() {
      if (image600UrlBuilder_ == null) {
        image600UrlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getImage600Url(),
                getParentForChildren(),
                isClean());
        image600Url_ = null;
      }
      return image600UrlBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.ProfileImage)
  }

  // @@protoc_insertion_point(class_scope:common.ProfileImage)
  private static final com.talking.grpc.common.ProfileImage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talking.grpc.common.ProfileImage();
  }

  public static com.talking.grpc.common.ProfileImage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProfileImage>
      PARSER = new com.google.protobuf.AbstractParser<ProfileImage>() {
    public ProfileImage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProfileImage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProfileImage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProfileImage> getParserForType() {
    return PARSER;
  }

  public com.talking.grpc.common.ProfileImage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

