// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.talking.grpc.common;

public interface ProfileImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ProfileImage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  boolean hasImageOriginalUrl();
  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  com.google.protobuf.StringValue getImageOriginalUrl();
  /**
   * <code>.google.protobuf.StringValue imageOriginalUrl = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getImageOriginalUrlOrBuilder();

  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  boolean hasImage100Url();
  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  com.google.protobuf.StringValue getImage100Url();
  /**
   * <code>.google.protobuf.StringValue image100Url = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getImage100UrlOrBuilder();

  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  boolean hasImage300Url();
  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  com.google.protobuf.StringValue getImage300Url();
  /**
   * <code>.google.protobuf.StringValue image300Url = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getImage300UrlOrBuilder();

  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  boolean hasImage600Url();
  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  com.google.protobuf.StringValue getImage600Url();
  /**
   * <code>.google.protobuf.StringValue image600Url = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getImage600UrlOrBuilder();
}
