// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.talking.grpc.common;

/**
 * Protobuf type {@code common.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    id_ = 0L;
    name_ = "";
    genderType_ = 0;
    age_ = 0;
    pr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            genderType_ = rawValue;
            break;
          }
          case 32: {

            age_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            pr_ = s;
            break;
          }
          case 50: {
            com.talking.grpc.common.ProfileImage.Builder subBuilder = null;
            if (profileImage_ != null) {
              subBuilder = profileImage_.toBuilder();
            }
            profileImage_ = input.readMessage(com.talking.grpc.common.ProfileImage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(profileImage_);
              profileImage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastOnlineDatetime_ != null) {
              subBuilder = lastOnlineDatetime_.toBuilder();
            }
            lastOnlineDatetime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastOnlineDatetime_);
              lastOnlineDatetime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (created_ != null) {
              subBuilder = created_.toBuilder();
            }
            created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(created_);
              created_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (modified_ != null) {
              subBuilder = modified_.toBuilder();
            }
            modified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modified_);
              modified_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talking.grpc.common.Commons.internal_static_common_User_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talking.grpc.common.Commons.internal_static_common_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talking.grpc.common.User.class, com.talking.grpc.common.User.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDERTYPE_FIELD_NUMBER = 3;
  private int genderType_;
  /**
   * <code>.common.GenderType genderType = 3;</code>
   */
  public int getGenderTypeValue() {
    return genderType_;
  }
  /**
   * <code>.common.GenderType genderType = 3;</code>
   */
  public com.talking.grpc.common.GenderType getGenderType() {
    com.talking.grpc.common.GenderType result = com.talking.grpc.common.GenderType.valueOf(genderType_);
    return result == null ? com.talking.grpc.common.GenderType.UNRECOGNIZED : result;
  }

  public static final int AGE_FIELD_NUMBER = 4;
  private int age_;
  /**
   * <code>int32 age = 4;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int PR_FIELD_NUMBER = 5;
  private volatile java.lang.Object pr_;
  /**
   * <code>string pr = 5;</code>
   */
  public java.lang.String getPr() {
    java.lang.Object ref = pr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pr_ = s;
      return s;
    }
  }
  /**
   * <code>string pr = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPrBytes() {
    java.lang.Object ref = pr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFILEIMAGE_FIELD_NUMBER = 6;
  private com.talking.grpc.common.ProfileImage profileImage_;
  /**
   * <code>.common.ProfileImage profileImage = 6;</code>
   */
  public boolean hasProfileImage() {
    return profileImage_ != null;
  }
  /**
   * <code>.common.ProfileImage profileImage = 6;</code>
   */
  public com.talking.grpc.common.ProfileImage getProfileImage() {
    return profileImage_ == null ? com.talking.grpc.common.ProfileImage.getDefaultInstance() : profileImage_;
  }
  /**
   * <code>.common.ProfileImage profileImage = 6;</code>
   */
  public com.talking.grpc.common.ProfileImageOrBuilder getProfileImageOrBuilder() {
    return getProfileImage();
  }

  public static final int LASTONLINEDATETIME_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp lastOnlineDatetime_;
  /**
   * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
   */
  public boolean hasLastOnlineDatetime() {
    return lastOnlineDatetime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
   */
  public com.google.protobuf.Timestamp getLastOnlineDatetime() {
    return lastOnlineDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastOnlineDatetime_;
  }
  /**
   * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getLastOnlineDatetimeOrBuilder() {
    return getLastOnlineDatetime();
  }

  public static final int CREATED_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp created_;
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public boolean hasCreated() {
    return created_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return getCreated();
  }

  public static final int MODIFIED_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp modified_;
  /**
   * <code>.google.protobuf.Timestamp modified = 9;</code>
   */
  public boolean hasModified() {
    return modified_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 9;</code>
   */
  public com.google.protobuf.Timestamp getModified() {
    return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 9;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
    return getModified();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (genderType_ != com.talking.grpc.common.GenderType.MALE.getNumber()) {
      output.writeEnum(3, genderType_);
    }
    if (age_ != 0) {
      output.writeInt32(4, age_);
    }
    if (!getPrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pr_);
    }
    if (profileImage_ != null) {
      output.writeMessage(6, getProfileImage());
    }
    if (lastOnlineDatetime_ != null) {
      output.writeMessage(7, getLastOnlineDatetime());
    }
    if (created_ != null) {
      output.writeMessage(8, getCreated());
    }
    if (modified_ != null) {
      output.writeMessage(9, getModified());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (genderType_ != com.talking.grpc.common.GenderType.MALE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, genderType_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, age_);
    }
    if (!getPrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pr_);
    }
    if (profileImage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getProfileImage());
    }
    if (lastOnlineDatetime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLastOnlineDatetime());
    }
    if (created_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCreated());
    }
    if (modified_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getModified());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talking.grpc.common.User)) {
      return super.equals(obj);
    }
    com.talking.grpc.common.User other = (com.talking.grpc.common.User) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && genderType_ == other.genderType_;
    result = result && (getAge()
        == other.getAge());
    result = result && getPr()
        .equals(other.getPr());
    result = result && (hasProfileImage() == other.hasProfileImage());
    if (hasProfileImage()) {
      result = result && getProfileImage()
          .equals(other.getProfileImage());
    }
    result = result && (hasLastOnlineDatetime() == other.hasLastOnlineDatetime());
    if (hasLastOnlineDatetime()) {
      result = result && getLastOnlineDatetime()
          .equals(other.getLastOnlineDatetime());
    }
    result = result && (hasCreated() == other.hasCreated());
    if (hasCreated()) {
      result = result && getCreated()
          .equals(other.getCreated());
    }
    result = result && (hasModified() == other.hasModified());
    if (hasModified()) {
      result = result && getModified()
          .equals(other.getModified());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + GENDERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + genderType_;
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + PR_FIELD_NUMBER;
    hash = (53 * hash) + getPr().hashCode();
    if (hasProfileImage()) {
      hash = (37 * hash) + PROFILEIMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getProfileImage().hashCode();
    }
    if (hasLastOnlineDatetime()) {
      hash = (37 * hash) + LASTONLINEDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getLastOnlineDatetime().hashCode();
    }
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    if (hasModified()) {
      hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getModified().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talking.grpc.common.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.common.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.common.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.common.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.common.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.common.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talking.grpc.common.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.User)
      com.talking.grpc.common.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talking.grpc.common.Commons.internal_static_common_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talking.grpc.common.Commons.internal_static_common_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talking.grpc.common.User.class, com.talking.grpc.common.User.Builder.class);
    }

    // Construct using com.talking.grpc.common.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      genderType_ = 0;

      age_ = 0;

      pr_ = "";

      if (profileImageBuilder_ == null) {
        profileImage_ = null;
      } else {
        profileImage_ = null;
        profileImageBuilder_ = null;
      }
      if (lastOnlineDatetimeBuilder_ == null) {
        lastOnlineDatetime_ = null;
      } else {
        lastOnlineDatetime_ = null;
        lastOnlineDatetimeBuilder_ = null;
      }
      if (createdBuilder_ == null) {
        created_ = null;
      } else {
        created_ = null;
        createdBuilder_ = null;
      }
      if (modifiedBuilder_ == null) {
        modified_ = null;
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talking.grpc.common.Commons.internal_static_common_User_descriptor;
    }

    public com.talking.grpc.common.User getDefaultInstanceForType() {
      return com.talking.grpc.common.User.getDefaultInstance();
    }

    public com.talking.grpc.common.User build() {
      com.talking.grpc.common.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.talking.grpc.common.User buildPartial() {
      com.talking.grpc.common.User result = new com.talking.grpc.common.User(this);
      result.id_ = id_;
      result.name_ = name_;
      result.genderType_ = genderType_;
      result.age_ = age_;
      result.pr_ = pr_;
      if (profileImageBuilder_ == null) {
        result.profileImage_ = profileImage_;
      } else {
        result.profileImage_ = profileImageBuilder_.build();
      }
      if (lastOnlineDatetimeBuilder_ == null) {
        result.lastOnlineDatetime_ = lastOnlineDatetime_;
      } else {
        result.lastOnlineDatetime_ = lastOnlineDatetimeBuilder_.build();
      }
      if (createdBuilder_ == null) {
        result.created_ = created_;
      } else {
        result.created_ = createdBuilder_.build();
      }
      if (modifiedBuilder_ == null) {
        result.modified_ = modified_;
      } else {
        result.modified_ = modifiedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talking.grpc.common.User) {
        return mergeFrom((com.talking.grpc.common.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talking.grpc.common.User other) {
      if (other == com.talking.grpc.common.User.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.genderType_ != 0) {
        setGenderTypeValue(other.getGenderTypeValue());
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (!other.getPr().isEmpty()) {
        pr_ = other.pr_;
        onChanged();
      }
      if (other.hasProfileImage()) {
        mergeProfileImage(other.getProfileImage());
      }
      if (other.hasLastOnlineDatetime()) {
        mergeLastOnlineDatetime(other.getLastOnlineDatetime());
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      if (other.hasModified()) {
        mergeModified(other.getModified());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talking.grpc.common.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talking.grpc.common.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int genderType_ = 0;
    /**
     * <code>.common.GenderType genderType = 3;</code>
     */
    public int getGenderTypeValue() {
      return genderType_;
    }
    /**
     * <code>.common.GenderType genderType = 3;</code>
     */
    public Builder setGenderTypeValue(int value) {
      genderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.common.GenderType genderType = 3;</code>
     */
    public com.talking.grpc.common.GenderType getGenderType() {
      com.talking.grpc.common.GenderType result = com.talking.grpc.common.GenderType.valueOf(genderType_);
      return result == null ? com.talking.grpc.common.GenderType.UNRECOGNIZED : result;
    }
    /**
     * <code>.common.GenderType genderType = 3;</code>
     */
    public Builder setGenderType(com.talking.grpc.common.GenderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      genderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.common.GenderType genderType = 3;</code>
     */
    public Builder clearGenderType() {
      
      genderType_ = 0;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 4;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 4;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 4;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pr_ = "";
    /**
     * <code>string pr = 5;</code>
     */
    public java.lang.String getPr() {
      java.lang.Object ref = pr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrBytes() {
      java.lang.Object ref = pr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pr = 5;</code>
     */
    public Builder setPr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pr = 5;</code>
     */
    public Builder clearPr() {
      
      pr_ = getDefaultInstance().getPr();
      onChanged();
      return this;
    }
    /**
     * <code>string pr = 5;</code>
     */
    public Builder setPrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pr_ = value;
      onChanged();
      return this;
    }

    private com.talking.grpc.common.ProfileImage profileImage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.ProfileImage, com.talking.grpc.common.ProfileImage.Builder, com.talking.grpc.common.ProfileImageOrBuilder> profileImageBuilder_;
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public boolean hasProfileImage() {
      return profileImageBuilder_ != null || profileImage_ != null;
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public com.talking.grpc.common.ProfileImage getProfileImage() {
      if (profileImageBuilder_ == null) {
        return profileImage_ == null ? com.talking.grpc.common.ProfileImage.getDefaultInstance() : profileImage_;
      } else {
        return profileImageBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public Builder setProfileImage(com.talking.grpc.common.ProfileImage value) {
      if (profileImageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profileImage_ = value;
        onChanged();
      } else {
        profileImageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public Builder setProfileImage(
        com.talking.grpc.common.ProfileImage.Builder builderForValue) {
      if (profileImageBuilder_ == null) {
        profileImage_ = builderForValue.build();
        onChanged();
      } else {
        profileImageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public Builder mergeProfileImage(com.talking.grpc.common.ProfileImage value) {
      if (profileImageBuilder_ == null) {
        if (profileImage_ != null) {
          profileImage_ =
            com.talking.grpc.common.ProfileImage.newBuilder(profileImage_).mergeFrom(value).buildPartial();
        } else {
          profileImage_ = value;
        }
        onChanged();
      } else {
        profileImageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public Builder clearProfileImage() {
      if (profileImageBuilder_ == null) {
        profileImage_ = null;
        onChanged();
      } else {
        profileImage_ = null;
        profileImageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public com.talking.grpc.common.ProfileImage.Builder getProfileImageBuilder() {
      
      onChanged();
      return getProfileImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    public com.talking.grpc.common.ProfileImageOrBuilder getProfileImageOrBuilder() {
      if (profileImageBuilder_ != null) {
        return profileImageBuilder_.getMessageOrBuilder();
      } else {
        return profileImage_ == null ?
            com.talking.grpc.common.ProfileImage.getDefaultInstance() : profileImage_;
      }
    }
    /**
     * <code>.common.ProfileImage profileImage = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.ProfileImage, com.talking.grpc.common.ProfileImage.Builder, com.talking.grpc.common.ProfileImageOrBuilder> 
        getProfileImageFieldBuilder() {
      if (profileImageBuilder_ == null) {
        profileImageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.talking.grpc.common.ProfileImage, com.talking.grpc.common.ProfileImage.Builder, com.talking.grpc.common.ProfileImageOrBuilder>(
                getProfileImage(),
                getParentForChildren(),
                isClean());
        profileImage_ = null;
      }
      return profileImageBuilder_;
    }

    private com.google.protobuf.Timestamp lastOnlineDatetime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastOnlineDatetimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public boolean hasLastOnlineDatetime() {
      return lastOnlineDatetimeBuilder_ != null || lastOnlineDatetime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public com.google.protobuf.Timestamp getLastOnlineDatetime() {
      if (lastOnlineDatetimeBuilder_ == null) {
        return lastOnlineDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastOnlineDatetime_;
      } else {
        return lastOnlineDatetimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public Builder setLastOnlineDatetime(com.google.protobuf.Timestamp value) {
      if (lastOnlineDatetimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastOnlineDatetime_ = value;
        onChanged();
      } else {
        lastOnlineDatetimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public Builder setLastOnlineDatetime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastOnlineDatetimeBuilder_ == null) {
        lastOnlineDatetime_ = builderForValue.build();
        onChanged();
      } else {
        lastOnlineDatetimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public Builder mergeLastOnlineDatetime(com.google.protobuf.Timestamp value) {
      if (lastOnlineDatetimeBuilder_ == null) {
        if (lastOnlineDatetime_ != null) {
          lastOnlineDatetime_ =
            com.google.protobuf.Timestamp.newBuilder(lastOnlineDatetime_).mergeFrom(value).buildPartial();
        } else {
          lastOnlineDatetime_ = value;
        }
        onChanged();
      } else {
        lastOnlineDatetimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public Builder clearLastOnlineDatetime() {
      if (lastOnlineDatetimeBuilder_ == null) {
        lastOnlineDatetime_ = null;
        onChanged();
      } else {
        lastOnlineDatetime_ = null;
        lastOnlineDatetimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastOnlineDatetimeBuilder() {
      
      onChanged();
      return getLastOnlineDatetimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastOnlineDatetimeOrBuilder() {
      if (lastOnlineDatetimeBuilder_ != null) {
        return lastOnlineDatetimeBuilder_.getMessageOrBuilder();
      } else {
        return lastOnlineDatetime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastOnlineDatetime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastOnlineDatetime = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastOnlineDatetimeFieldBuilder() {
      if (lastOnlineDatetimeBuilder_ == null) {
        lastOnlineDatetimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastOnlineDatetime(),
                getParentForChildren(),
                isClean());
        lastOnlineDatetime_ = null;
      }
      return lastOnlineDatetimeBuilder_;
    }

    private com.google.protobuf.Timestamp created_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public boolean hasCreated() {
      return createdBuilder_ != null || created_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
        onChanged();
      } else {
        createdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
        onChanged();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (created_ != null) {
          created_ =
            com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
        } else {
          created_ = value;
        }
        onChanged();
      } else {
        createdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder clearCreated() {
      if (createdBuilder_ == null) {
        created_ = null;
        onChanged();
      } else {
        created_ = null;
        createdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }

    private com.google.protobuf.Timestamp modified_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public boolean hasModified() {
      return modifiedBuilder_ != null || modified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public com.google.protobuf.Timestamp getModified() {
      if (modifiedBuilder_ == null) {
        return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      } else {
        return modifiedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public Builder setModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modified_ = value;
        onChanged();
      } else {
        modifiedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public Builder setModified(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedBuilder_ == null) {
        modified_ = builderForValue.build();
        onChanged();
      } else {
        modifiedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public Builder mergeModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (modified_ != null) {
          modified_ =
            com.google.protobuf.Timestamp.newBuilder(modified_).mergeFrom(value).buildPartial();
        } else {
          modified_ = value;
        }
        onChanged();
      } else {
        modifiedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public Builder clearModified() {
      if (modifiedBuilder_ == null) {
        modified_ = null;
        onChanged();
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getModifiedBuilder() {
      
      onChanged();
      return getModifiedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
      if (modifiedBuilder_ != null) {
        return modifiedBuilder_.getMessageOrBuilder();
      } else {
        return modified_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getModifiedFieldBuilder() {
      if (modifiedBuilder_ == null) {
        modifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getModified(),
                getParentForChildren(),
                isClean());
        modified_ = null;
      }
      return modifiedBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.User)
  }

  // @@protoc_insertion_point(class_scope:common.User)
  private static final com.talking.grpc.common.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talking.grpc.common.User();
  }

  public static com.talking.grpc.common.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  public com.talking.grpc.common.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

