// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calling.proto

package com.talking.grpc.calling;

public final class Calling {
  private Calling() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_StartCallingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_StartCallingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_StartCallingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_StartCallingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_ReceiveCallingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_ReceiveCallingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_EndCallingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_EndCallingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_ContinueCallingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_ContinueCallingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calling_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calling_StatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcalling.proto\022\007calling\032\033google/protobu" +
      "f/empty.proto\"\'\n\023StartCallingRequest\022\020\n\010" +
      "toUserId\030\001 \001(\003\"K\n\024StartCallingResponse\0223" +
      "\n\nresultType\030\001 \001(\0162\037.calling.StartCallin" +
      "gResultType\"=\n\025ReceiveCallingRequest\022\022\n\n" +
      "fromUserId\030\001 \001(\003\022\020\n\010toUserId\030\002 \001(\003\"9\n\021En" +
      "dCallingRequest\022\022\n\nfromUserId\030\001 \001(\003\022\020\n\010t" +
      "oUserId\030\002 \001(\003\">\n\026ContinueCallingRequest\022" +
      "\022\n\nfromUserId\030\001 \001(\003\022\020\n\010toUserId\030\002 \001(\003\"^\n" +
      "\016StatusResponse\022\022\n\nfromUserId\030\001 \001(\003\022\020\n\010t" +
      "oUserId\030\002 \001(\003\022&\n\006status\030\003 \001(\0162\026.calling." +
      "CallingStatus*=\n\026StartCallingResultType\022" +
      "\013\n\007SUCCESS\020\000\022\026\n\022TO_USER_IN_TALKING\020\001*3\n\r" +
      "CallingStatus\022\014\n\010STARTING\020\000\022\013\n\007TALKING\020\001" +
      "\022\007\n\003END\020\0022\200\003\n\016CallingService\022K\n\014StartCal" +
      "ling\022\034.calling.StartCallingRequest\032\035.cal" +
      "ling.StartCallingResponse\022H\n\016ReceiveCall" +
      "ing\022\036.calling.ReceiveCallingRequest\032\026.go" +
      "ogle.protobuf.Empty\022@\n\nEndCalling\022\032.call" +
      "ing.EndCallingRequest\032\026.google.protobuf." +
      "Empty\022J\n\017ContinueCalling\022\037.calling.Conti" +
      "nueCallingRequest\032\026.google.protobuf.Empt" +
      "y\022I\n\024ReceiveCallingStatus\022\026.google.proto" +
      "buf.Empty\032\027.calling.StatusResponse0\001B\034\n\030" +
      "com.talking.grpc.callingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_calling_StartCallingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calling_StartCallingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_StartCallingRequest_descriptor,
        new java.lang.String[] { "ToUserId", });
    internal_static_calling_StartCallingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calling_StartCallingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_StartCallingResponse_descriptor,
        new java.lang.String[] { "ResultType", });
    internal_static_calling_ReceiveCallingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calling_ReceiveCallingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_ReceiveCallingRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_calling_EndCallingRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calling_EndCallingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_EndCallingRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_calling_ContinueCallingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_calling_ContinueCallingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_ContinueCallingRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_calling_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_calling_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calling_StatusResponse_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "Status", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
