// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calling.proto

package com.talking.grpc.calling;

public interface StartCallingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calling.StartCallingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.calling.StartCallingResultType resultType = 1;</code>
   */
  int getResultTypeValue();
  /**
   * <code>.calling.StartCallingResultType resultType = 1;</code>
   */
  com.talking.grpc.calling.StartCallingResultType getResultType();
}
