// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calling.proto

package com.talking.grpc.calling;

/**
 * Protobuf enum {@code calling.StartCallingResultType}
 */
public enum StartCallingResultType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <code>TO_USER_IN_TALKING = 1;</code>
   */
  TO_USER_IN_TALKING(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <code>TO_USER_IN_TALKING = 1;</code>
   */
  public static final int TO_USER_IN_TALKING_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StartCallingResultType valueOf(int value) {
    return forNumber(value);
  }

  public static StartCallingResultType forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return TO_USER_IN_TALKING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StartCallingResultType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StartCallingResultType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StartCallingResultType>() {
          public StartCallingResultType findValueByNumber(int number) {
            return StartCallingResultType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.talking.grpc.calling.Calling.getDescriptor().getEnumTypes().get(0);
  }

  private static final StartCallingResultType[] VALUES = values();

  public static StartCallingResultType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StartCallingResultType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:calling.StartCallingResultType)
}

