// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calling.proto

package com.talking.grpc.calling;

public interface StartCallingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calling.StartCallingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 toUserId = 1;</code>
   */
  long getToUserId();
}
