// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calling.proto

package com.talking.grpc.calling;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calling.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fromUserId = 1;</code>
   */
  long getFromUserId();

  /**
   * <code>int64 toUserId = 2;</code>
   */
  long getToUserId();

  /**
   * <code>.calling.CallingStatus status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.calling.CallingStatus status = 3;</code>
   */
  com.talking.grpc.calling.CallingStatus getStatus();
}
