// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.talking.grpc.user;

public interface RegisterUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.RegisterUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apiToken = 1;</code>
   */
  java.lang.String getApiToken();
  /**
   * <code>string apiToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getApiTokenBytes();

  /**
   * <code>.common.User user = 2;</code>
   */
  boolean hasUser();
  /**
   * <code>.common.User user = 2;</code>
   */
  com.talking.grpc.common.User getUser();
  /**
   * <code>.common.User user = 2;</code>
   */
  com.talking.grpc.common.UserOrBuilder getUserOrBuilder();
}
