// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.talking.grpc.user;

/**
 * Protobuf type {@code account.RegisterUserResponse}
 */
public  final class RegisterUserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:account.RegisterUserResponse)
    RegisterUserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterUserResponse.newBuilder() to construct.
  private RegisterUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterUserResponse() {
    apiToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterUserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            apiToken_ = s;
            break;
          }
          case 18: {
            com.talking.grpc.common.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.talking.grpc.common.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talking.grpc.user.Account.internal_static_account_RegisterUserResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talking.grpc.user.Account.internal_static_account_RegisterUserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talking.grpc.user.RegisterUserResponse.class, com.talking.grpc.user.RegisterUserResponse.Builder.class);
  }

  public static final int APITOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object apiToken_;
  /**
   * <code>string apiToken = 1;</code>
   */
  public java.lang.String getApiToken() {
    java.lang.Object ref = apiToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiToken_ = s;
      return s;
    }
  }
  /**
   * <code>string apiToken = 1;</code>
   */
  public com.google.protobuf.ByteString
      getApiTokenBytes() {
    java.lang.Object ref = apiToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIELD_NUMBER = 2;
  private com.talking.grpc.common.User user_;
  /**
   * <code>.common.User user = 2;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.common.User user = 2;</code>
   */
  public com.talking.grpc.common.User getUser() {
    return user_ == null ? com.talking.grpc.common.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.common.User user = 2;</code>
   */
  public com.talking.grpc.common.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getApiTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, apiToken_);
    }
    if (user_ != null) {
      output.writeMessage(2, getUser());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getApiTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, apiToken_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talking.grpc.user.RegisterUserResponse)) {
      return super.equals(obj);
    }
    com.talking.grpc.user.RegisterUserResponse other = (com.talking.grpc.user.RegisterUserResponse) obj;

    boolean result = true;
    result = result && getApiToken()
        .equals(other.getApiToken());
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APITOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getApiToken().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.user.RegisterUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talking.grpc.user.RegisterUserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code account.RegisterUserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:account.RegisterUserResponse)
      com.talking.grpc.user.RegisterUserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talking.grpc.user.Account.internal_static_account_RegisterUserResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talking.grpc.user.Account.internal_static_account_RegisterUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talking.grpc.user.RegisterUserResponse.class, com.talking.grpc.user.RegisterUserResponse.Builder.class);
    }

    // Construct using com.talking.grpc.user.RegisterUserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      apiToken_ = "";

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talking.grpc.user.Account.internal_static_account_RegisterUserResponse_descriptor;
    }

    public com.talking.grpc.user.RegisterUserResponse getDefaultInstanceForType() {
      return com.talking.grpc.user.RegisterUserResponse.getDefaultInstance();
    }

    public com.talking.grpc.user.RegisterUserResponse build() {
      com.talking.grpc.user.RegisterUserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.talking.grpc.user.RegisterUserResponse buildPartial() {
      com.talking.grpc.user.RegisterUserResponse result = new com.talking.grpc.user.RegisterUserResponse(this);
      result.apiToken_ = apiToken_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talking.grpc.user.RegisterUserResponse) {
        return mergeFrom((com.talking.grpc.user.RegisterUserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talking.grpc.user.RegisterUserResponse other) {
      if (other == com.talking.grpc.user.RegisterUserResponse.getDefaultInstance()) return this;
      if (!other.getApiToken().isEmpty()) {
        apiToken_ = other.apiToken_;
        onChanged();
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talking.grpc.user.RegisterUserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talking.grpc.user.RegisterUserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object apiToken_ = "";
    /**
     * <code>string apiToken = 1;</code>
     */
    public java.lang.String getApiToken() {
      java.lang.Object ref = apiToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string apiToken = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiTokenBytes() {
      java.lang.Object ref = apiToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string apiToken = 1;</code>
     */
    public Builder setApiToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      apiToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string apiToken = 1;</code>
     */
    public Builder clearApiToken() {
      
      apiToken_ = getDefaultInstance().getApiToken();
      onChanged();
      return this;
    }
    /**
     * <code>string apiToken = 1;</code>
     */
    public Builder setApiTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      apiToken_ = value;
      onChanged();
      return this;
    }

    private com.talking.grpc.common.User user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> userBuilder_;
    /**
     * <code>.common.User user = 2;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public com.talking.grpc.common.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.talking.grpc.common.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public Builder setUser(com.talking.grpc.common.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public Builder setUser(
        com.talking.grpc.common.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public Builder mergeUser(com.talking.grpc.common.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.talking.grpc.common.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public com.talking.grpc.common.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    public com.talking.grpc.common.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.talking.grpc.common.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.common.User user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:account.RegisterUserResponse)
  }

  // @@protoc_insertion_point(class_scope:account.RegisterUserResponse)
  private static final com.talking.grpc.user.RegisterUserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talking.grpc.user.RegisterUserResponse();
  }

  public static com.talking.grpc.user.RegisterUserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterUserResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterUserResponse>() {
    public RegisterUserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterUserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterUserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterUserResponse> getParserForType() {
    return PARSER;
  }

  public com.talking.grpc.user.RegisterUserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

