// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.talking.grpc.user;

public interface UpdateProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.UpdateProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * google.protobufにすると、nullを設定できる。
   * optional扱いにできる。
   * </pre>
   *
   * <code>.google.protobuf.StringValue name = 1;</code>
   */
  boolean hasName();
  /**
   * <pre>
   * google.protobufにすると、nullを設定できる。
   * optional扱いにできる。
   * </pre>
   *
   * <code>.google.protobuf.StringValue name = 1;</code>
   */
  com.google.protobuf.StringValue getName();
  /**
   * <pre>
   * google.protobufにすると、nullを設定できる。
   * optional扱いにできる。
   * </pre>
   *
   * <code>.google.protobuf.StringValue name = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  boolean hasAge();
  /**
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  com.google.protobuf.Int32Value getAge();
  /**
   * <code>.google.protobuf.Int32Value age = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getAgeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue pr = 3;</code>
   */
  boolean hasPr();
  /**
   * <code>.google.protobuf.StringValue pr = 3;</code>
   */
  com.google.protobuf.StringValue getPr();
  /**
   * <code>.google.protobuf.StringValue pr = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPrOrBuilder();
}
