// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block.proto

package com.talking.grpc.block;

public interface BlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:block.BlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 toUserId = 1;</code>
   */
  long getToUserId();
}
