// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_notify.proto

package com.talking.grpc.push_notify;

public final class PushNotify {
  private PushNotify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_push_notify_SavePushTokenIosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_push_notify_SavePushTokenIosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_push_notify_UpdateNotifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_push_notify_UpdateNotifyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021push_notify.proto\022\013push_notify\032\033google" +
      "/protobuf/empty.proto\".\n\027SavePushTokenIo" +
      "sRequest\022\023\n\013deviceToken\030\001 \001(\t\"(\n\023UpdateN" +
      "otifyRequest\022\021\n\tisEnabled\030\001 \001(\0102\257\001\n\021Push" +
      "NotifyService\022P\n\020SavePushTokenIos\022$.push" +
      "_notify.SavePushTokenIosRequest\032\026.google" +
      ".protobuf.Empty\022H\n\014UpdateNotify\022 .push_n" +
      "otify.UpdateNotifyRequest\032\026.google.proto" +
      "buf.EmptyB \n\034com.talking.grpc.push_notif" +
      "yP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_push_notify_SavePushTokenIosRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_push_notify_SavePushTokenIosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_push_notify_SavePushTokenIosRequest_descriptor,
        new java.lang.String[] { "DeviceToken", });
    internal_static_push_notify_UpdateNotifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_push_notify_UpdateNotifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_push_notify_UpdateNotifyRequest_descriptor,
        new java.lang.String[] { "IsEnabled", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
