// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_notify.proto

package com.talking.grpc.push_notify;

public interface SavePushTokenIosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:push_notify.SavePushTokenIosRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceToken = 1;</code>
   */
  java.lang.String getDeviceToken();
  /**
   * <code>string deviceToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTokenBytes();
}
