// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_notify.proto

package com.talking.grpc.push_notify;

/**
 * Protobuf type {@code push_notify.UpdateNotifyRequest}
 */
public  final class UpdateNotifyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:push_notify.UpdateNotifyRequest)
    UpdateNotifyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateNotifyRequest.newBuilder() to construct.
  private UpdateNotifyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateNotifyRequest() {
    isEnabled_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateNotifyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isEnabled_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talking.grpc.push_notify.PushNotify.internal_static_push_notify_UpdateNotifyRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talking.grpc.push_notify.PushNotify.internal_static_push_notify_UpdateNotifyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talking.grpc.push_notify.UpdateNotifyRequest.class, com.talking.grpc.push_notify.UpdateNotifyRequest.Builder.class);
  }

  public static final int ISENABLED_FIELD_NUMBER = 1;
  private boolean isEnabled_;
  /**
   * <code>bool isEnabled = 1;</code>
   */
  public boolean getIsEnabled() {
    return isEnabled_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isEnabled_ != false) {
      output.writeBool(1, isEnabled_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isEnabled_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talking.grpc.push_notify.UpdateNotifyRequest)) {
      return super.equals(obj);
    }
    com.talking.grpc.push_notify.UpdateNotifyRequest other = (com.talking.grpc.push_notify.UpdateNotifyRequest) obj;

    boolean result = true;
    result = result && (getIsEnabled()
        == other.getIsEnabled());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsEnabled());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.push_notify.UpdateNotifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talking.grpc.push_notify.UpdateNotifyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code push_notify.UpdateNotifyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:push_notify.UpdateNotifyRequest)
      com.talking.grpc.push_notify.UpdateNotifyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talking.grpc.push_notify.PushNotify.internal_static_push_notify_UpdateNotifyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talking.grpc.push_notify.PushNotify.internal_static_push_notify_UpdateNotifyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talking.grpc.push_notify.UpdateNotifyRequest.class, com.talking.grpc.push_notify.UpdateNotifyRequest.Builder.class);
    }

    // Construct using com.talking.grpc.push_notify.UpdateNotifyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isEnabled_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talking.grpc.push_notify.PushNotify.internal_static_push_notify_UpdateNotifyRequest_descriptor;
    }

    public com.talking.grpc.push_notify.UpdateNotifyRequest getDefaultInstanceForType() {
      return com.talking.grpc.push_notify.UpdateNotifyRequest.getDefaultInstance();
    }

    public com.talking.grpc.push_notify.UpdateNotifyRequest build() {
      com.talking.grpc.push_notify.UpdateNotifyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.talking.grpc.push_notify.UpdateNotifyRequest buildPartial() {
      com.talking.grpc.push_notify.UpdateNotifyRequest result = new com.talking.grpc.push_notify.UpdateNotifyRequest(this);
      result.isEnabled_ = isEnabled_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talking.grpc.push_notify.UpdateNotifyRequest) {
        return mergeFrom((com.talking.grpc.push_notify.UpdateNotifyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talking.grpc.push_notify.UpdateNotifyRequest other) {
      if (other == com.talking.grpc.push_notify.UpdateNotifyRequest.getDefaultInstance()) return this;
      if (other.getIsEnabled() != false) {
        setIsEnabled(other.getIsEnabled());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talking.grpc.push_notify.UpdateNotifyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talking.grpc.push_notify.UpdateNotifyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isEnabled_ ;
    /**
     * <code>bool isEnabled = 1;</code>
     */
    public boolean getIsEnabled() {
      return isEnabled_;
    }
    /**
     * <code>bool isEnabled = 1;</code>
     */
    public Builder setIsEnabled(boolean value) {
      
      isEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isEnabled = 1;</code>
     */
    public Builder clearIsEnabled() {
      
      isEnabled_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:push_notify.UpdateNotifyRequest)
  }

  // @@protoc_insertion_point(class_scope:push_notify.UpdateNotifyRequest)
  private static final com.talking.grpc.push_notify.UpdateNotifyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talking.grpc.push_notify.UpdateNotifyRequest();
  }

  public static com.talking.grpc.push_notify.UpdateNotifyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateNotifyRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateNotifyRequest>() {
    public UpdateNotifyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateNotifyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateNotifyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateNotifyRequest> getParserForType() {
    return PARSER;
  }

  public com.talking.grpc.push_notify.UpdateNotifyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

