// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_notify.proto

package com.talking.grpc.push_notify;

public interface UpdateNotifyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:push_notify.UpdateNotifyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isEnabled = 1;</code>
   */
  boolean getIsEnabled();
}
