// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.talking.grpc.report;

public interface PostReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:report.PostReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 toUserId = 1;</code>
   */
  long getToUserId();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
