// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.talking.grpc.report;

public final class Report {
  private Report() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_report_PostReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_report_PostReportRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014report.proto\022\006report\032\033google/protobuf/" +
      "empty.proto\"6\n\021PostReportRequest\022\020\n\010toUs" +
      "erId\030\001 \001(\003\022\017\n\007message\030\002 \001(\t2P\n\rReportSer" +
      "vice\022?\n\nPostReport\022\031.report.PostReportRe" +
      "quest\032\026.google.protobuf.EmptyB\033\n\027com.tal" +
      "king.grpc.reportP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_report_PostReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_report_PostReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_report_PostReportRequest_descriptor,
        new java.lang.String[] { "ToUserId", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
