// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.talking.grpc.chat;

public interface AllChatMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.AllChatMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 minMessageId = 1;</code>
   */
  long getMinMessageId();
}
