// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.talking.grpc.chat;

public interface AllChatMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.AllChatMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.User users = 1;</code>
   */
  java.util.List<com.talking.grpc.common.User> 
      getUsersList();
  /**
   * <code>repeated .common.User users = 1;</code>
   */
  com.talking.grpc.common.User getUsers(int index);
  /**
   * <code>repeated .common.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .common.User users = 1;</code>
   */
  java.util.List<? extends com.talking.grpc.common.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .common.User users = 1;</code>
   */
  com.talking.grpc.common.UserOrBuilder getUsersOrBuilder(
      int index);

  /**
   * <code>repeated .chat.ChatMessage messages = 2;</code>
   */
  java.util.List<com.talking.grpc.chat.ChatMessage> 
      getMessagesList();
  /**
   * <code>repeated .chat.ChatMessage messages = 2;</code>
   */
  com.talking.grpc.chat.ChatMessage getMessages(int index);
  /**
   * <code>repeated .chat.ChatMessage messages = 2;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .chat.ChatMessage messages = 2;</code>
   */
  java.util.List<? extends com.talking.grpc.chat.ChatMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .chat.ChatMessage messages = 2;</code>
   */
  com.talking.grpc.chat.ChatMessageOrBuilder getMessagesOrBuilder(
      int index);
}
