// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.talking.grpc.chat;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 fromUserId = 2;</code>
   */
  long getFromUserId();

  /**
   * <code>int64 toUserId = 3;</code>
   */
  long getToUserId();

  /**
   * <code>string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
}
