// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.talking.grpc.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_ReceiveMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_ReceiveMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_AllChatMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_AllChatMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_AllChatMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_AllChatMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\004chat\032\033google/protobuf/empt" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\032\rcommons.proto\"7\n\022SendMessageRequest\022\020\n" +
      "\010toUserId\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\"~\n\026Rece" +
      "iveMessageResponse\022&\n\013chatMessage\030\001 \001(\0132" +
      "\021.chat.ChatMessage\022\036\n\010fromUser\030\002 \001(\0132\014.c" +
      "ommon.User\022\034\n\006toUser\030\003 \001(\0132\014.common.User" +
      "\"-\n\025AllChatMessageRequest\022\024\n\014minMessageI" +
      "d\030\001 \001(\003\"Z\n\026AllChatMessageResponse\022\033\n\005use" +
      "rs\030\001 \003(\0132\014.common.User\022#\n\010messages\030\002 \003(\013" +
      "2\021.chat.ChatMessage\"z\n\013ChatMessage\022\n\n\002id" +
      "\030\001 \001(\003\022\022\n\nfromUserId\030\002 \001(\003\022\020\n\010toUserId\030\003" +
      " \001(\003\022\017\n\007message\030\004 \001(\t\022(\n\004date\030\005 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp2\345\001\n\013ChatService\022" +
      "?\n\013SendMessage\022\030.chat.SendMessageRequest" +
      "\032\026.google.protobuf.Empty\022H\n\016ReceiveMessa" +
      "ge\022\026.google.protobuf.Empty\032\034.chat.Receiv" +
      "eMessageResponse0\001\022K\n\016GetAllMessages\022\033.c" +
      "hat.AllChatMessageRequest\032\034.chat.AllChat" +
      "MessageResponseB\031\n\025com.talking.grpc.chat" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.talking.grpc.common.Commons.getDescriptor(),
        }, assigner);
    internal_static_chat_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_SendMessageRequest_descriptor,
        new java.lang.String[] { "ToUserId", "Message", });
    internal_static_chat_ReceiveMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_ReceiveMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_ReceiveMessageResponse_descriptor,
        new java.lang.String[] { "ChatMessage", "FromUser", "ToUser", });
    internal_static_chat_AllChatMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chat_AllChatMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_AllChatMessageRequest_descriptor,
        new java.lang.String[] { "MinMessageId", });
    internal_static_chat_AllChatMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chat_AllChatMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_AllChatMessageResponse_descriptor,
        new java.lang.String[] { "Users", "Messages", });
    internal_static_chat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_ChatMessage_descriptor,
        new java.lang.String[] { "Id", "FromUserId", "ToUserId", "Message", "Date", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.talking.grpc.common.Commons.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
