// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.talking.grpc.chat;

/**
 * Protobuf type {@code chat.ReceiveMessageResponse}
 */
public  final class ReceiveMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chat.ReceiveMessageResponse)
    ReceiveMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReceiveMessageResponse.newBuilder() to construct.
  private ReceiveMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReceiveMessageResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReceiveMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.talking.grpc.chat.ChatMessage.Builder subBuilder = null;
            if (chatMessage_ != null) {
              subBuilder = chatMessage_.toBuilder();
            }
            chatMessage_ = input.readMessage(com.talking.grpc.chat.ChatMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chatMessage_);
              chatMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.talking.grpc.common.User.Builder subBuilder = null;
            if (fromUser_ != null) {
              subBuilder = fromUser_.toBuilder();
            }
            fromUser_ = input.readMessage(com.talking.grpc.common.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fromUser_);
              fromUser_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.talking.grpc.common.User.Builder subBuilder = null;
            if (toUser_ != null) {
              subBuilder = toUser_.toBuilder();
            }
            toUser_ = input.readMessage(com.talking.grpc.common.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(toUser_);
              toUser_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talking.grpc.chat.Chat.internal_static_chat_ReceiveMessageResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talking.grpc.chat.Chat.internal_static_chat_ReceiveMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talking.grpc.chat.ReceiveMessageResponse.class, com.talking.grpc.chat.ReceiveMessageResponse.Builder.class);
  }

  public static final int CHATMESSAGE_FIELD_NUMBER = 1;
  private com.talking.grpc.chat.ChatMessage chatMessage_;
  /**
   * <code>.chat.ChatMessage chatMessage = 1;</code>
   */
  public boolean hasChatMessage() {
    return chatMessage_ != null;
  }
  /**
   * <code>.chat.ChatMessage chatMessage = 1;</code>
   */
  public com.talking.grpc.chat.ChatMessage getChatMessage() {
    return chatMessage_ == null ? com.talking.grpc.chat.ChatMessage.getDefaultInstance() : chatMessage_;
  }
  /**
   * <code>.chat.ChatMessage chatMessage = 1;</code>
   */
  public com.talking.grpc.chat.ChatMessageOrBuilder getChatMessageOrBuilder() {
    return getChatMessage();
  }

  public static final int FROMUSER_FIELD_NUMBER = 2;
  private com.talking.grpc.common.User fromUser_;
  /**
   * <code>.common.User fromUser = 2;</code>
   */
  public boolean hasFromUser() {
    return fromUser_ != null;
  }
  /**
   * <code>.common.User fromUser = 2;</code>
   */
  public com.talking.grpc.common.User getFromUser() {
    return fromUser_ == null ? com.talking.grpc.common.User.getDefaultInstance() : fromUser_;
  }
  /**
   * <code>.common.User fromUser = 2;</code>
   */
  public com.talking.grpc.common.UserOrBuilder getFromUserOrBuilder() {
    return getFromUser();
  }

  public static final int TOUSER_FIELD_NUMBER = 3;
  private com.talking.grpc.common.User toUser_;
  /**
   * <code>.common.User toUser = 3;</code>
   */
  public boolean hasToUser() {
    return toUser_ != null;
  }
  /**
   * <code>.common.User toUser = 3;</code>
   */
  public com.talking.grpc.common.User getToUser() {
    return toUser_ == null ? com.talking.grpc.common.User.getDefaultInstance() : toUser_;
  }
  /**
   * <code>.common.User toUser = 3;</code>
   */
  public com.talking.grpc.common.UserOrBuilder getToUserOrBuilder() {
    return getToUser();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chatMessage_ != null) {
      output.writeMessage(1, getChatMessage());
    }
    if (fromUser_ != null) {
      output.writeMessage(2, getFromUser());
    }
    if (toUser_ != null) {
      output.writeMessage(3, getToUser());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chatMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChatMessage());
    }
    if (fromUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFromUser());
    }
    if (toUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getToUser());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talking.grpc.chat.ReceiveMessageResponse)) {
      return super.equals(obj);
    }
    com.talking.grpc.chat.ReceiveMessageResponse other = (com.talking.grpc.chat.ReceiveMessageResponse) obj;

    boolean result = true;
    result = result && (hasChatMessage() == other.hasChatMessage());
    if (hasChatMessage()) {
      result = result && getChatMessage()
          .equals(other.getChatMessage());
    }
    result = result && (hasFromUser() == other.hasFromUser());
    if (hasFromUser()) {
      result = result && getFromUser()
          .equals(other.getFromUser());
    }
    result = result && (hasToUser() == other.hasToUser());
    if (hasToUser()) {
      result = result && getToUser()
          .equals(other.getToUser());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChatMessage()) {
      hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getChatMessage().hashCode();
    }
    if (hasFromUser()) {
      hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
      hash = (53 * hash) + getFromUser().hashCode();
    }
    if (hasToUser()) {
      hash = (37 * hash) + TOUSER_FIELD_NUMBER;
      hash = (53 * hash) + getToUser().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talking.grpc.chat.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talking.grpc.chat.ReceiveMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chat.ReceiveMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chat.ReceiveMessageResponse)
      com.talking.grpc.chat.ReceiveMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talking.grpc.chat.Chat.internal_static_chat_ReceiveMessageResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talking.grpc.chat.Chat.internal_static_chat_ReceiveMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talking.grpc.chat.ReceiveMessageResponse.class, com.talking.grpc.chat.ReceiveMessageResponse.Builder.class);
    }

    // Construct using com.talking.grpc.chat.ReceiveMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (chatMessageBuilder_ == null) {
        chatMessage_ = null;
      } else {
        chatMessage_ = null;
        chatMessageBuilder_ = null;
      }
      if (fromUserBuilder_ == null) {
        fromUser_ = null;
      } else {
        fromUser_ = null;
        fromUserBuilder_ = null;
      }
      if (toUserBuilder_ == null) {
        toUser_ = null;
      } else {
        toUser_ = null;
        toUserBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talking.grpc.chat.Chat.internal_static_chat_ReceiveMessageResponse_descriptor;
    }

    public com.talking.grpc.chat.ReceiveMessageResponse getDefaultInstanceForType() {
      return com.talking.grpc.chat.ReceiveMessageResponse.getDefaultInstance();
    }

    public com.talking.grpc.chat.ReceiveMessageResponse build() {
      com.talking.grpc.chat.ReceiveMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.talking.grpc.chat.ReceiveMessageResponse buildPartial() {
      com.talking.grpc.chat.ReceiveMessageResponse result = new com.talking.grpc.chat.ReceiveMessageResponse(this);
      if (chatMessageBuilder_ == null) {
        result.chatMessage_ = chatMessage_;
      } else {
        result.chatMessage_ = chatMessageBuilder_.build();
      }
      if (fromUserBuilder_ == null) {
        result.fromUser_ = fromUser_;
      } else {
        result.fromUser_ = fromUserBuilder_.build();
      }
      if (toUserBuilder_ == null) {
        result.toUser_ = toUser_;
      } else {
        result.toUser_ = toUserBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talking.grpc.chat.ReceiveMessageResponse) {
        return mergeFrom((com.talking.grpc.chat.ReceiveMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talking.grpc.chat.ReceiveMessageResponse other) {
      if (other == com.talking.grpc.chat.ReceiveMessageResponse.getDefaultInstance()) return this;
      if (other.hasChatMessage()) {
        mergeChatMessage(other.getChatMessage());
      }
      if (other.hasFromUser()) {
        mergeFromUser(other.getFromUser());
      }
      if (other.hasToUser()) {
        mergeToUser(other.getToUser());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talking.grpc.chat.ReceiveMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talking.grpc.chat.ReceiveMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.talking.grpc.chat.ChatMessage chatMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.chat.ChatMessage, com.talking.grpc.chat.ChatMessage.Builder, com.talking.grpc.chat.ChatMessageOrBuilder> chatMessageBuilder_;
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public boolean hasChatMessage() {
      return chatMessageBuilder_ != null || chatMessage_ != null;
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public com.talking.grpc.chat.ChatMessage getChatMessage() {
      if (chatMessageBuilder_ == null) {
        return chatMessage_ == null ? com.talking.grpc.chat.ChatMessage.getDefaultInstance() : chatMessage_;
      } else {
        return chatMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public Builder setChatMessage(com.talking.grpc.chat.ChatMessage value) {
      if (chatMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chatMessage_ = value;
        onChanged();
      } else {
        chatMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public Builder setChatMessage(
        com.talking.grpc.chat.ChatMessage.Builder builderForValue) {
      if (chatMessageBuilder_ == null) {
        chatMessage_ = builderForValue.build();
        onChanged();
      } else {
        chatMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public Builder mergeChatMessage(com.talking.grpc.chat.ChatMessage value) {
      if (chatMessageBuilder_ == null) {
        if (chatMessage_ != null) {
          chatMessage_ =
            com.talking.grpc.chat.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
        } else {
          chatMessage_ = value;
        }
        onChanged();
      } else {
        chatMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public Builder clearChatMessage() {
      if (chatMessageBuilder_ == null) {
        chatMessage_ = null;
        onChanged();
      } else {
        chatMessage_ = null;
        chatMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public com.talking.grpc.chat.ChatMessage.Builder getChatMessageBuilder() {
      
      onChanged();
      return getChatMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    public com.talking.grpc.chat.ChatMessageOrBuilder getChatMessageOrBuilder() {
      if (chatMessageBuilder_ != null) {
        return chatMessageBuilder_.getMessageOrBuilder();
      } else {
        return chatMessage_ == null ?
            com.talking.grpc.chat.ChatMessage.getDefaultInstance() : chatMessage_;
      }
    }
    /**
     * <code>.chat.ChatMessage chatMessage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.chat.ChatMessage, com.talking.grpc.chat.ChatMessage.Builder, com.talking.grpc.chat.ChatMessageOrBuilder> 
        getChatMessageFieldBuilder() {
      if (chatMessageBuilder_ == null) {
        chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.talking.grpc.chat.ChatMessage, com.talking.grpc.chat.ChatMessage.Builder, com.talking.grpc.chat.ChatMessageOrBuilder>(
                getChatMessage(),
                getParentForChildren(),
                isClean());
        chatMessage_ = null;
      }
      return chatMessageBuilder_;
    }

    private com.talking.grpc.common.User fromUser_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> fromUserBuilder_;
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public boolean hasFromUser() {
      return fromUserBuilder_ != null || fromUser_ != null;
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public com.talking.grpc.common.User getFromUser() {
      if (fromUserBuilder_ == null) {
        return fromUser_ == null ? com.talking.grpc.common.User.getDefaultInstance() : fromUser_;
      } else {
        return fromUserBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public Builder setFromUser(com.talking.grpc.common.User value) {
      if (fromUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fromUser_ = value;
        onChanged();
      } else {
        fromUserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public Builder setFromUser(
        com.talking.grpc.common.User.Builder builderForValue) {
      if (fromUserBuilder_ == null) {
        fromUser_ = builderForValue.build();
        onChanged();
      } else {
        fromUserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public Builder mergeFromUser(com.talking.grpc.common.User value) {
      if (fromUserBuilder_ == null) {
        if (fromUser_ != null) {
          fromUser_ =
            com.talking.grpc.common.User.newBuilder(fromUser_).mergeFrom(value).buildPartial();
        } else {
          fromUser_ = value;
        }
        onChanged();
      } else {
        fromUserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public Builder clearFromUser() {
      if (fromUserBuilder_ == null) {
        fromUser_ = null;
        onChanged();
      } else {
        fromUser_ = null;
        fromUserBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public com.talking.grpc.common.User.Builder getFromUserBuilder() {
      
      onChanged();
      return getFromUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    public com.talking.grpc.common.UserOrBuilder getFromUserOrBuilder() {
      if (fromUserBuilder_ != null) {
        return fromUserBuilder_.getMessageOrBuilder();
      } else {
        return fromUser_ == null ?
            com.talking.grpc.common.User.getDefaultInstance() : fromUser_;
      }
    }
    /**
     * <code>.common.User fromUser = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> 
        getFromUserFieldBuilder() {
      if (fromUserBuilder_ == null) {
        fromUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder>(
                getFromUser(),
                getParentForChildren(),
                isClean());
        fromUser_ = null;
      }
      return fromUserBuilder_;
    }

    private com.talking.grpc.common.User toUser_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> toUserBuilder_;
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public boolean hasToUser() {
      return toUserBuilder_ != null || toUser_ != null;
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public com.talking.grpc.common.User getToUser() {
      if (toUserBuilder_ == null) {
        return toUser_ == null ? com.talking.grpc.common.User.getDefaultInstance() : toUser_;
      } else {
        return toUserBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public Builder setToUser(com.talking.grpc.common.User value) {
      if (toUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toUser_ = value;
        onChanged();
      } else {
        toUserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public Builder setToUser(
        com.talking.grpc.common.User.Builder builderForValue) {
      if (toUserBuilder_ == null) {
        toUser_ = builderForValue.build();
        onChanged();
      } else {
        toUserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public Builder mergeToUser(com.talking.grpc.common.User value) {
      if (toUserBuilder_ == null) {
        if (toUser_ != null) {
          toUser_ =
            com.talking.grpc.common.User.newBuilder(toUser_).mergeFrom(value).buildPartial();
        } else {
          toUser_ = value;
        }
        onChanged();
      } else {
        toUserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public Builder clearToUser() {
      if (toUserBuilder_ == null) {
        toUser_ = null;
        onChanged();
      } else {
        toUser_ = null;
        toUserBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public com.talking.grpc.common.User.Builder getToUserBuilder() {
      
      onChanged();
      return getToUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    public com.talking.grpc.common.UserOrBuilder getToUserOrBuilder() {
      if (toUserBuilder_ != null) {
        return toUserBuilder_.getMessageOrBuilder();
      } else {
        return toUser_ == null ?
            com.talking.grpc.common.User.getDefaultInstance() : toUser_;
      }
    }
    /**
     * <code>.common.User toUser = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder> 
        getToUserFieldBuilder() {
      if (toUserBuilder_ == null) {
        toUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.talking.grpc.common.User, com.talking.grpc.common.User.Builder, com.talking.grpc.common.UserOrBuilder>(
                getToUser(),
                getParentForChildren(),
                isClean());
        toUser_ = null;
      }
      return toUserBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chat.ReceiveMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:chat.ReceiveMessageResponse)
  private static final com.talking.grpc.chat.ReceiveMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talking.grpc.chat.ReceiveMessageResponse();
  }

  public static com.talking.grpc.chat.ReceiveMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReceiveMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReceiveMessageResponse>() {
    public ReceiveMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReceiveMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReceiveMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReceiveMessageResponse> getParserForType() {
    return PARSER;
  }

  public com.talking.grpc.chat.ReceiveMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

